### ISSUE TITLE
Add YAML formatters

### ISSUE THREAD

**Issue by andrewlock** [WebApiContrib/WebAPIContrib.Core#103]
I saw that @damienbod recently added Protobuf formatters to the project, and I remembered that I had a Yaml output formatter lying around. Mostly for interest I created a project in the same style as the ProtoBuf project, in case you wanted to add it in?

I realise YAML format is pretty unusual for a wire format, but I needed it at one point (can't remember why now!) so someone might find it useful 😄 

Accompanying PR to follow.

**Comment by filipw** [comment]
Fixed by #104
