### ISSUE TITLE
CSV under .NETStandard 2.0 library running on .NET 4.6.1 gives exceptions

### ISSUE THREAD

**Issue by SGStino** [WebApiContrib/WebAPIContrib.Core#111]
Method not found: 'Microsoft.Net.Http.Headers.MediaTypeHeaderValue Microsoft.Net.Http.Headers.MediaTypeHeaderValue.Parse(System.String)'.

Seems to be caused by: https://github.com/aspnet/HttpAbstractions/issues/847
They changed the method implementations from string to StringSegment.

And there seems to be an implic cast in StringSegment, fixing it compile time, but giving two distinct assemblies at runtime.
```csharp
public static implicit operator StringSegment(string value)
{
    return new StringSegment(value);
}
```
when compiling the WebApiContrib.Core solution locally in vs2017 i seem to get:
```msil
.maxstack 2
.locals init (
[0] bool V_0
)

IL_0000: ldarg.0  this
IL_0001: call         instance void [Microsoft.AspNetCore.Mvc.Core]Microsoft.AspNetCore.Mvc.Formatters.InputFormatter::.ctor()
IL_0006: nop          
IL_0007: nop          
IL_0008: ldarg.0  this
IL_0009: call         instance class [Microsoft.AspNetCore.Mvc.Core]Microsoft.AspNetCore.Mvc.Formatters.MediaTypeCollection [Microsoft.AspNetCore.Mvc.Core]Microsoft.AspNetCore.Mvc.Formatters.InputFormatter::get_SupportedMediaTypes()
IL_000e: ldstr        "text/csv"
IL_0013: call         valuetype [Microsoft.Extensions.Primitives]Microsoft.Extensions.Primitives.StringSegment [Microsoft.Extensions.Primitives]Microsoft.Extensions.Primitives.StringSegment::op_Implicit(string)
IL_0018: call         class [Microsoft.Net.Http.Headers]Microsoft.Net.Http.Headers.MediaTypeHeaderValue [Microsoft.Net.Http.Headers]Microsoft.Net.Http.Headers.MediaTypeHeaderValue::Parse(valuetype [Microsoft.Extensions.Primitives]Microsoft.Extensions.Primitives.StringSegment)
IL_001d: callvirt     instance void [Microsoft.AspNetCore.Mvc.Core]Microsoft.AspNetCore.Mvc.Formatters.MediaTypeCollection::Add(class [Microsoft.Net.Http.Headers]Microsoft.Net.Http.Headers.MediaTypeHeaderValue)
IL_0022: nop          
IL_0023: ldarg.1  csvFormatterOptions
IL_0024: ldnull       
IL_0025: ceq          
IL_0027: stloc.0  V_0
IL_0028: ldloc.0  V_0
IL_0029: brfalse.s    IL_0037
IL_002b: nop          
IL_002c: ldstr        "csvFormatterOptions"
IL_0031: newobj       instance void [mscorlib]System.ArgumentNullException::.ctor(string)
IL_0036: throw        
IL_0037: ldarg.0  this
IL_0038: ldarg.1  csvFormatterOptions
IL_0039: stfld        class WebApiContrib.Core.Formatter.Csv.CsvFormatterOptions WebApiContrib.Core.Formatter.Csv.CsvInputFormatter::_options
IL_003e: ret   
``` 
when looking into dll that msbuild got copied into my output folder i find:
```msil
.maxstack 8
il_0000: ldarg.0  this
il_0001: call         instance void [microsoft.aspnetcore.mvc.core]microsoft.aspnetcore.mvc.formatters.inputformatter::.ctor()
il_0006: ldarg.0  this
il_0007: call         instance class [microsoft.aspnetcore.mvc.core]microsoft.aspnetcore.mvc.formatters.mediatypecollection [microsoft.aspnetcore.mvc.core]microsoft.aspnetcore.mvc.formatters.inputformatter::get_supportedmediatypes()
il_000c: ldstr        "text/csv"
il_0011: call         instance class [microsoft.net.http.headers]microsoft.net.http.headers.mediatypeheadervalue [microsoft.net.http.headers]microsoft.net.http.headers.mediatypeheadervalue::parse(string)
il_0016: callvirt     instance void [microsoft.aspnetcore.mvc.core]microsoft.aspnetcore.mvc.formatters.mediatypecollection::add(class [microsoft.net.http.headers]microsoft.net.http.headers.mediatypeheadervalue)
il_001b: ldarg.1  csvformatteroptions
il_001c: brtrue.s     il_0029
il_001e: ldstr        "csvformatteroptions"
il_0023: newobj       instance void [mscorlib]system.argumentnullexception::.ctor(string)
il_0028: throw        
il_0029: ldarg.0  this
il_002a: ldarg.1  csvformatteroptions
il_002b: stfld        class webapicontrib.core.formatter.csv.csvformatteroptions webapicontrib.core.formatter.csv.csvinputformatter::_options
il_0030: ret   
```
this seems to match with the net451 dll in the nuget. 

So i'm guessing here that msbuild says: oh, net461, that's compatible with net451, lets use that dll, and doesn't even bother with .netstandard2.0 anymore.
However, because our libary uses .NETStandard it also copies over those dlls to the output folder, so it doesn't use the Framework 4.6.1 dlls but the Standard 2.0 dlls.

Our project structure is:

```
"ServiceHost" (.NET Framework 4.6.1 executable csproj) --project reference--> "ServiceHosting" (.NET Standard 2.0 class library csproj) --nuget reference--> "WebAPIContrib.Core.Formatter.Csv" 
```

I assume this is an issue for nuget to fix (if at all possible), and WebAPIContrib to work around?

**Comment by SGStino** [comment]
https://github.com/NuGet/Home/issues/5370 

> NuGet can't determine exactly which is going to be a better match for the user so it leaves it up to the package author. 

So I'm guessing it's final there.

**Comment by damienbod** [comment]
You should use the https://www.nuget.org/packages/WebApiContrib.Core.Formatter.Csv/1.0.3 with .NET 4.61

The netstandard 2.0 seems not the work with 4.6.1.

**Comment by SGStino** [comment]
it works, if you manually take the correct dll

**Comment by filipw** [comment]
@damienbod I think the simplest solution is to drop .netstandard1.6 and .net451 and just target netstandard2.0
It will not be the same, since netstandard2.0 supports .net461, but I don't think it's a big deal 😀

**Comment by jdluzen** [comment]
I am getting this as well when targeting `netcoreapp2.0` using `WebApiContrib.Core.Formatter.Bson`. I read through the comments here, but am not entirely sure what the workaround is. Could someone please clarify?

**Comment by damienbod** [comment]
I will create a new version which only supported 2.0. Nuget and .NET Standard seem to have problems with different versions.

**Comment by filipw** [comment]
I think the entire `WebApiContrib.Core` should move to `netstandard2.0` - same as MVC did for all its packages. If some is on older MVC, they can use the older packages, and if someone is on latest MVC, well, then that would be the only way to get latest `WebApiContrib.Core` 😊

**Comment by damienbod** [comment]
@SGStino 
Only supports netstandard 2.0 

https://www.nuget.org/packages/WebApiContrib.Core.Formatter.Csv/

**Comment by SGStino** [comment]
thanks! that'll make life easier for deploys 👍

**Comment by rmccabe24** [comment]
Hi, I'm using .net framework 4.6.2 - which version of your library should I reference?  v1.0.3 gives an error:

An error occurred while starting the application.
MissingMethodException: Method not found: 'Void Microsoft.Net.Http.Headers.MediaTypeHeaderValue..ctor(System.String)'.
WebApiContrib.Core.Formatter.Csv.CsvFormatterMvcBuilderExtensions+<>c.<AddCsvSerializerFormatters>b__1_0(FormatterMappings m)

Unfortunately, I'm restricted to use this version of .net Framework due to this being an existing project and really wanted to use your library!  Thanks in advance for any info.

**Comment by damienbod** [comment]
@rmccabe24 
Hi Robert If you can't use the .NET Standard 2 version, with the version 1.0.3, you can reference the net451 version directly in your project and it will work. 

Greetings Damien

**Comment by rmccabe24** [comment]
I'm trying to use it in a net4.6.2 (I'm tied into this project type) - so cant change to .net Standard 2.  There's no other version of your lib that's supported with .net Framework?

**Comment by damienbod** [comment]
The nuget package 1.0.3 has 2 dlls. If you open the csproj file, remove the csv. Then add the proper dll directly. For some reason the wrong dll is used.

Greetings Damien

**Comment by rmccabe24** [comment]
Hi Damien, it isn't overly clear what needs to be done or how to do it so I will have to look to use an alternative solution to csv output, unfortunately.  Thanks anyway.

**Comment by damienbod** [comment]
Ok, you could also use the code directly :)

**Comment by kentico-jiris** [comment]
FYI I have the same problem, with Jsonp
.net sdk version: 2.0
targeting: net47
WebApiContrib.Core.Formatter.Jsonp version: 1.0.0

**Comment by seccijr** [comment]
For those receiving the error _System.AggregateException : One or more errors occurred. (Method not found: 'Microsoft.Net.Http.Headers.MediaTypeHeaderValue Microsoft.Net.Http.Headers.MediaTypeHeaderValue.Parse(System.String)'_ when running Test project please add explicitly reference to Microsoft.AspNetCore.Mvc and Microsoft.AspNetCore.StaticFiles to your dependencies:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0" />
....
  </ItemGroup>
</Project>

```
Do it in your csproj file of your Test project.
