### ISSUE TITLE
Extensions for IMvcCoreBuilder

### ISSUE THREAD

**Issue by iAlexanderMoon** [WebApiContrib/WebAPIContrib.Core#117]
Currently there are extensions for IMvcBuilder however if startup is onc configured with services.AddMvcCore and the builder is an IMvcCoreBuilder the extensions are not available. Is there a technical reason for this? Is there another way to call the existing extension I'm missing or would these extensions need to be added?

**Comment by filipw** [comment]
no, they would have to be added. Even MVC itself ships with many extension methods added twice, for both builders

**Comment by iAlexanderMoon** [comment]
Would you like a PR?

**Comment by filipw** [comment]
sure!
