### ISSUE TITLE
WebApiContrib.Core.Formatter.Protobuf -  Can't configure RuntimeTypeModel

### ISSUE THREAD

**Issue by derrickcrowne** [WebApiContrib/WebAPIContrib.Core#119]
I use a surrogate to add support for DateTimeOffset to protobuf-net, such as this:

`RuntimeTypeModel.Default.Add(typeof(DateTimeOffset), false).SetSurrogate(typeof(DateTimeOffsetSurrogate));`

The input and output formatters create their own RuntimeTypeModels but don't provide any access to change the configuration.

**Comment by lehne** [comment]
I think I'm running into this as well. Not deserializing properly and I think this is the issue.

**Comment by lehne** [comment]
Actually, just figured it out. The Model is available statically. Just add this:
`ProtobufInputFormatter.Model.Add(typeof(DateTimeOffset), false).SetSurrogate(typeof(DateTimeOffsetSurrogate));`

**Comment by derrickcrowne** [comment]
Thanks, that worked for me.
