### ISSUE TITLE
Use GZIP compression with Protobuf?

### ISSUE THREAD

**Issue by ArcadeRenegade** [WebApiContrib/WebAPIContrib.Core#136]
Hi,

Is it possible to use GZIP compression with WebApiContrib.Core.Formatter.Protobuf?

I have GZIP compression middleware set up in my ASP.NET Core API app but I can't seem to get Protobuf responses to use GZIP.

I tested and JSON responses are using GZIP as expected.

![image](https://user-images.githubusercontent.com/13874898/40630472-cae7a24a-6287-11e8-994b-7c6c97e6d87f.png)

JSON w/ GZIP

![image](https://user-images.githubusercontent.com/13874898/40630494-ece2d86a-6287-11e8-9032-2269b1da3d66.png)

Protobuf w/o GZIP

![image](https://user-images.githubusercontent.com/13874898/40630507-fbf53c08-6287-11e8-8a57-3d6a7cb7d6fe.png)

Thanks!

**Comment by khellang** [comment]
If you're talking about Microsoft's Microsoft.AspNetCore.ResponseCompression, you should take a look at how you can add custom content types. See https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-2.0&tabs=aspnetcore2x#mime-types

**Comment by ArcadeRenegade** [comment]
Worked! Thanks.
