### ISSUE TITLE
Add option to add excel delimiter header meta data

### ISSUE THREAD

**Issue by sravimohan** [WebApiContrib/WebAPIContrib.Core#144]
Adding the option to include "sep ={_options.CsvDelimiter}" as the first line lets the file to be opened directly in excel.

suggested change (line 90):
https://github.com/sravimohan/WebAPIContrib.Core/blob/master/src/WebApiContrib.Core.Formatter.Csv/CsvOutputFormatter.cs.

Pl. let me know if I can do a PR.

**Comment by filipw** [comment]
Thanks - please open a PR

**Comment by sravimohan** [comment]
Have created the PR . Thank you.

**Comment by filipw** [comment]
fixed with #145
