### ISSUE TITLE
Using CsvFormatter and gzip compression together is not working

### ISSUE THREAD

**Issue by bryanjhogan** [WebApiContrib/WebAPIContrib.Core#147]
I am working on a .Net Core 2.1.2 Web API application, and using WebApiContrib.Core.Formatter.Csv 2.0.5

My startup.cs looks like this - 

```
CsvFormatterOptions csvFormatterOptions = new CsvFormatterOptions() {CsvDelimiter = ","};
services.AddMvc()
        .AddCsvSerializerFormatters(csvFormatterOptions)
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

services.Configure<GzipCompressionProviderOptions>(options => options.Level = System.IO.Compression.CompressionLevel.Optimal);
services.AddResponseCompression();
```
___
If I make a request for a csv by adding the below to my header, it works fine. 
`Accept: text/csv`
___
If I make a request for compressed json, it works fine. 
```
Accept-Encoding: gzip
Accept: text/json
```
___
BUT, if I make a request for compressed csv, I get back uncompressed csv. 
```
Accept-Encoding: gzip
Accept: text/csv
```

**Comment by damienbod** [comment]
thanks, support for this should be added.

**Comment by filipw** [comment]
@bryanjhogan this is not a limitation of the WebApiContrib formatter, it's just the response compression middleware must be configured to light up for CSV too.  Out of the box, it will only react to HTML/CSS/JS/JSON media types.

This should do the trick:
```
services.AddResponseCompression(options => 
{
    options.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(new[] { "text/csv" });
});
```

**Comment by bryanjhogan** [comment]
Thanks. Working now.
