### ISSUE TITLE
Do we want to take dependency on Microsoft.AspNetCore.Mvc.WebApiCompatShim?

### ISSUE THREAD

**Issue by filipw** [WebApiContrib/WebAPIContrib.Core#16]
There is a lot of interesting things allowing folks to bridge between Web API and MVC Core in [Microsoft.AspNetCore.Mvc.WebApiCompatShim](https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim)

As a result, there are a bunch of interesting things we could offer people _if only_ we decide to take dependency on it. I personally consider `WebApiCompatShim` more of a `WebApiConventions` but some folks might be put off by the name `shim`.

Thoughts?

**Comment by cecilphillip** [comment]
What are some of the things you're thinking about offering ? I don't see anything wrong with taking a dependency on it in an add-on package.

**Comment by filipw** [comment]
This can be handled on the per-feature basis if needed

**Comment by JoseMarcenaro** [comment]
Good question, filipw
IMHO, the more pressing question is whether to use it or not when building **a new** Web API project (I wouldn't mind using it for compatibility purposes)
I would assume that the required extensions / conventions (i.e. HttpError) will be added to MVC Core at some point, with the same or an enhanced implementation. But maybe that is not intended.
