### ISSUE TITLE
.Net Core 2.1.1 get error

### ISSUE THREAD

**Issue by sonphnt** [WebApiContrib/WebAPIContrib.Core#162]
Hi. I have just upgraded .net core 2.0 to 2.1 and got exception with 
"'System.Text.UTF8Encoding+UTF8EncodingSealed' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider

In startup.cs file I use this line
`services.AddMvc().AddCsvSerializerFormatters(new CsvFormatterOptions() { Encoding = Encoding.UTF8.ToString() });`

I am using version 2.0.7 of this package. How do I fix this problem? 
Thanks

**Comment by sonphnt** [comment]
Remove Encoding = Encoding.UTF8.ToString() then it works but how can I include UTF8 Support?

**Comment by damienbod** [comment]
I fix this tomorrow, and create a new package tomorrow

**Comment by damienbod** [comment]
https://www.nuget.org/packages/WebApiContrib.Core.Formatter.Csv/2.1.0

@sonphnt The config option is now:

 .AddCsvSerializerFormatters(new CsvFormatterOptions() { Encoding = Encoding.UTF8 })

Greetings Damien

**Comment by sonphnt** [comment]
Thanks @damienbod It worked perfectly.
