### ISSUE TITLE
Structural changes

### ISSUE THREAD

**Issue by filipw** [WebApiContrib/WebAPIContrib.Core#19]
- single repo for better code governance and better overview
- many solutions in a repo allowing folks to open and work only on the specific thing they want to work on - for example, each of the projects here https://github.com/WebApiContrib/WebAPIContrib.Core/tree/master/src should have its own solution file
- each of them can have separate versioning (no need for a shared version across all projects)
- multiple small nuget packages pushed from the repo (each project will have its own nuget)

cc @pedroreys @darrelmiller

**Comment by panesofglass** [comment]
:+1:

**Comment by damienbod** [comment]
How will you separate the features / packages?

- folder (pro feature)
--- sln file
--- src projects (test projects, sample projects, feature project)

Greetings Damien

**Comment by panesofglass** [comment]
@filipw how are you managing versions? `AssemblyInfo.cs` in each project? How is the version increment enforced?

**Comment by filipw** [comment]
these are project.jsons so there is no `AssemblyInfo` - each `project.json` has a `version` property

Would be nice to set it up in a way that you have RELEASE_NOTES.md, you document everything and bump versions there using markdown headers and then the build script parses that, updates project.json on the fly, builds the nuget package and injects the release notes there. That's the set up I've used in the past most often and it has worked really well.

**Comment by filipw** [comment]
But bottom line, it would be better to version each project separately since they have no cross dependencies

**Comment by filipw** [comment]
This is already in place
