### ISSUE TITLE
Add a CSV InputFormatter OutputFormatter

### ISSUE THREAD

**Issue by damienbod** [WebApiContrib/WebAPIContrib.Core#3]
@tugberkugurlu, @filipw All

Do you think this would be a good project for this repository. Robust input, output formatters could be created which can work with different types of arrays, collections, and maybe dictionaries.

Also different type of delimiters could be supported.

Some starting points:

https://github.com/damienbod/AspNetCoreCsvImportExport/tree/master/src/AspNetCoreCsvImportExport/Formatters

http://www.tugberkugurlu.com/archive/creating-custom-csvmediatypeformatter-in-asp-net-web-api-for-comma-separated-values-csv-format

https://github.com/filipw/aspnetcore-api-sample/tree/master/SampleApi/src/SampleApi/Formatters

What do you think?

Greetings Damien

**Comment by filipw** [comment]
yep, absolutely, this is exactly why this project has been created

**Comment by damienbod** [comment]
Ok, I'll create an initial version and create a pull request then.

Greetings Damien

**Comment by damienbod** [comment]
- First version will support  definition of delimiters in setup for example ',' or ';' => default is ';'
- Media type : "text/csv"
- support for  arrays, lists, collections with class containing properties or public fields only. 

Ok?

**Comment by filipw** [comment]
sure

**Comment by damienbod** [comment]
I have added a test sample to test the csv formatters.

Works now for Lists for classes with properties and the different configuration options.

If you want to see the latest version and give early feedback:

https://github.com/damienbod/WebAPIContrib.Core/tree/devCsvFormatters

TODO:
- support for classes with field properties
- support / test for array, collection types etc
- Unit tests or Integration tests
- downgrade to net451

When should I create the pull request, when I'm fully finished, or ...

Greetings Damien

**Comment by filipw** [comment]
> support for classes with field properties

imho this is not needed, this is very Java-like, I think it's safe to assume .NET POCOs always have public properties not public fields

also wouldn't worry about integration testing atm

**Comment by damienbod** [comment]
Ok, Array and IList now work for Input and output formatters

I'll create a pull request, and you can give me feedback. Thanks 

Greetings Damien

**Comment by filipw** [comment]
closed with #13 
For any outstanding changes, let's open new issues.
