### ISSUE TITLE
Add build scripts

### ISSUE THREAD

**Issue by filipw** [WebApiContrib/WebAPIContrib.Core#39]
Related to #6 and #11

**Comment by panesofglass** [comment]
I'll take a look later this week to see whether I can contribute a FAKE script to manage the builds.

**Comment by filipw** [comment]
thanks that would be great! I added this few days ago as a temp solution https://github.com/WebApiContrib/WebAPIContrib.Core/pull/41

it's FAKE + Fake.Dotnet (a wrapper around dotnet-cli). However Fake.Dotnet is windows only at the moment (since it has hardcoded references to Windows paths and to ps1 installation script).

I guess the solution would be to wrap the dotnet-cli commands with FAKE tasks

**Comment by panesofglass** [comment]
@filipw See https://github.com/dolly22/FAKE.Dotnet/issues/3. I imagine this will be resolved soon knowing @sforkmann. If not, I may pitch in to get it working. Wrapping commands is not that tough; I've done it a lot lately at work.

**Comment by panesofglass** [comment]
Looks like CAKE already has this covered: http://cakebuild.net/dsl/dotnetcore. In all fairness, I'm not sure either is necessary at this point. Seems easy enough to write simple bash and powershell scripts. Or would you prefer to have a single script for the build logic and just call it from those scripts?
