### ISSUE TITLE
Adapt WebPages to use IFileProvider

### ISSUE THREAD

**Issue by dazinator** [WebApiContrib/WebAPIContrib.Core#49]
Just came here after hearing about this project on the aspnet community standup!

Looks like sone nice stuff here.

I noticed the webpages stuff uses a router that checks the physical file system for existence of a cshtml file. Dont think there us any need for that, it should probably just use the IHostingEnvironment's content file provider (IFileProvider) instead. This will allow the cshtml file contents to live anywhere, including in embedded assemblies. I am happy to tackle this with a PR when I get some time?

**Comment by filipw** [comment]
Absolutely, that would be great!
