### ISSUE TITLE
addTagHelper directive and assembly name globbing

### ISSUE THREAD

**Issue by dazinator** [WebApiContrib/WebAPIContrib.Core#52]
I recently implemented an `ITagHelperTypeResolver` explained in [this post](http://darrelltunnell.net/blog/2016/07/25/aspnet-core-taghelper-s-a-better-addtaghelper-type-resolver/) that basically allows you to use `addTagHelper` directives like this

```
@addTagHelper "*, Plugin.*"
```

That will import all TagHelper's from all assemblies matching the glob.
As you reference new assemblies matching that glob, (or load them at runtime) any taghelper's within them will automatically be imported into the view.

The default asp.net implementation doesn't allow you to do that, you have to specify each assembly, as it only does globbing on the typename portion:

```
@addTagHelper "*, Plugin.Another"
@addTagHelper "*, Plugin.YetAnother"
```

This is quite handy for my situation, but not sure if you would be insterested in a PR for this, let me know.

**Comment by filipw** [comment]
Absolutely!

**Comment by dazinator** [comment]
Ok - where would you want this to live? I was thinking of adding it to the `WebAPiContrib.Core` project, and then adding a method to:

```
  public static class ServiceCollectionExtensions
    {
        public static void EnableAddTagHelperAssemblyGlobbing(this IServiceCollection services)
        {
           services.AddSingleton<ITagHelperTypeResolver, AssemblyNameGlobbingTagHelperTypeResolver>();

        }
    }

```

**Comment by dazinator** [comment]
Actually it might make sense putting this in `WebApiContrib.Core.WebPages` as that project has the dependency on `Razor` which I need.

**Comment by dazinator** [comment]
On second thoughts, I think perhaps adding a new project `WebApiContrib.Core.Razor` is merited. I'll submit a PR based on that.

**Comment by dazinator** [comment]
PR submitted

**Comment by dazinator** [comment]
I have noticed that in the `WebApiContrib.Core.Samples` project, if you browse to `/Markdown/Sample` - the markdown sample doesn't seem to work.. has this always been broken? I think it might have because I can't see any `addTagHelper` directive for the markdown tag helper anywhere. Perhaps it needs to be fixed or removed?
