### ISSUE TITLE
Update to .NET Core 1.1.0

### ISSUE THREAD

**Issue by damienbod** [WebApiContrib/WebAPIContrib.Core#78]
Would like to update to 1.1.0. 
@filipw All
Should we follow the LTS releases or the current for this? (I would prefer to follow the current).

https://www.microsoft.com/net/download/core

If we go with the current .NET Core will we update the versions to 1.1.0?

Greetings Damien

**Comment by filipw** [comment]
here is a good thread https://twitter.com/leastprivilege/status/801723059149357056

**Comment by damienbod** [comment]
These are security issues, do we use these anywhere? As we are just building libraries, this should not be a problem for devs using the packages from LTS. 

Maybe it makes sense to stick with the LTS.

I also require a new NuGet package for the https://www.nuget.org/packages/WebApiContrib.Core.Formatter.Csv/ 

(fix from the last pull request)

Greetings Damien

**Comment by filipw** [comment]
I added you as owner in nuget

**Comment by damienbod** [comment]
This account?
https://www.nuget.org/profiles/damienbod

**Comment by damienbod** [comment]
Think we sould do this together with msbuild
https://github.com/WebApiContrib/WebAPIContrib.Core/issues/84

**Comment by filipw** [comment]
sure, although this is orthogonal to compiling the lib from `csproj` or `project.json`
