### ISSUE TITLE
problem with localized data in CSV formatter

### ISSUE THREAD

**Issue by parmarnishant** [WebApiContrib/WebAPIContrib.Core#87]
How to set encoding for localized data ? 
My content is in german and french and file is not displaying localized strings.
It is configurable ?

**Comment by damienbod** [comment]
Is the format of the file correct?

Here's an example:
https://damienbod.com/2016/06/17/import-export-csv-in-asp-net-core/

**Comment by damienbod** [comment]
@parmarnishant @filipw 
Can we close this?

**Comment by FrancoisM** [comment]
Change this [line](https://github.com/WebApiContrib/WebAPIContrib.Core/blob/5179dab6fe2717fc309a9155cf2cc7369a612309/src/WebApiContrib.Core.Formatter.Csv/CsvInputFormatter.cs#L87) 
with 
`var reader = new StreamReader(stream, Encoding.GetEncoding("ISO-8859-1"));`

**Comment by damienbod** [comment]
Thanks, I'll fix this

**Comment by damienbod** [comment]
@FrancoisM  I plan to fix this at the weekend

**Comment by FrancoisM** [comment]
Don't harcode the string for encoding but make it a parameter of the ctor of your formatter or even better a field of CsvFormatterOptions.

**Comment by damienbod** [comment]
thanks, will do

**Comment by damienbod** [comment]
fixed in 2.0.2

https://www.nuget.org/packages/WebApiContrib.Core.Formatter.Csv/

Thanks reporting
