### ISSUE TITLE
clone and build solution not working

### ISSUE THREAD

**Issue by damienbod** [WebApiContrib/WebAPIContrib.Core#9]
When I checkout the project, I cannot build the project due to missing Redis dependencies.

WebApiContrib.Core.Concurrency.Integration.Tests

and 

WebApiContrib.Core.Concurrency.Redis

I think this should work per default, or at least a simple readme should be supplied.

Greetings Damien

**Comment by filipw** [comment]
the problem is with VS tooling as it can't handle `net451` vs `net46` framework monikers.
try running `dotnet build src\WebApiContrib.Core.Concurrency` from the command line and then rebuild in VS

**Comment by damienbod** [comment]
Did the trick, thanks, maybe I add a readme for this, what do you think?

**Comment by filipw** [comment]
I think the real solution is to align the monikers and replace all `net46` with `net451`. I am not sure why they are there in the first place but I assume that's by mistake

**Comment by damienbod** [comment]
Do we need to support 451? Why not just netstandard1.5? 462 will support this.

**Comment by filipw** [comment]
because MVC is cross compiled against 451 for the time being https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/project.json#L60 so you wanna support all users

**Comment by damienbod** [comment]
OK
